---
excludes:
  paths:
  - pattern: "tools/**"
    reason: "BUILD_TOOL_OF"
    comment: "This directory contains projects used to generate ORT configurations."
  - pattern: "evaluator-rules/build.gradle.kts"
    reason: "BUILD_TOOL_OF"
    comment: "This project is being used to provide IDE support for the evaluator.rules.kts file."
  - pattern: "notifications/build.gradle.kts"
    reason: "BUILD_TOOL_OF"
    comment: "This project is being used to provide IDE support for the example.notifications.kts file."
  - pattern: "**/*CONTRIBUTING*"
    reason: "DOCUMENTATION_OF"
    comment: "Those file help other contributors to devlop packages and do not contain licence information"