ort:
  scanner:
    skipConcluded: true
    archive:
      enabled: true
    options:
      # A map of maps from scanner class names to scanner-specific key-value pairs.
      ScanCode:
        # Command line options that affect the ScanCode output. If changed, stored scan results that were created with
        # different options are not reused.
        commandLine: '--copyright --license --info --strip-root --timeout 600'
